In [1]:
import numpy as np
import cv2 as cv
import argparse
from PIL import Image, ImageEnhance, ImageDraw 
import matplotlib.pyplot as plt
import os
import tensorflow as tf
import keras

In [2]:
def ROI(frame):
    
    face_classifier = cv.CascadeClassifier('haarcascade_frontalface_default.xml')
    gray = cv.cvtColor(frame, cv.COLOR_RGB2GRAY)
    faces = face_classifier.detectMultiScale(gray, 1.5, 5)
    x=0
    y=0
    w=0
    h=0
    max_area = 0
    for face in faces:
        x_t, y_t, w_t, h_t = face
        if w_t*h_t>max_area:
            max_area = w_t*h_t
            x,y,w,h = face
    
    return x,y,w,h

In [3]:
emotion = {
    '0' : 'Afraid',
    '1' : 'Angry',
    '2' : 'Disgust',
    '3' : 'Happy',
    '4' : 'Neutral',
    '5' : 'Sad',
    '6' : 'Surprise'
}

In [4]:
emotion_count = [0 for i in range(0,7)]
emotion_count

[0, 0, 0, 0, 0, 0, 0]

In [10]:
# def video_feed(directory):
model = keras.models.load_model("model_4.model")
cap = cv.VideoCapture('test.mp4')
t = 0
while cap.isOpened():
#         try:
    ret, frame = cap.read()
#             cv.imshow("Frame", frame)
    x,y,w,h = ROI(frame)
    croped_image = frame[x:x+w, y-20:y+h+20]
    frame = cv.rectangle(frame, (x,y-20), (x+w, y+h+20), (255,0,0), 2)
    if(cv.waitKey(2) == 13 & 0xFF):
        break
    img_array = cv.cvtColor(croped_image, cv.COLOR_BGR2GRAY)/255.0
    img_array = cv.resize(img_array, (48,48))
    img_array = np.array(img_array)

    img_array = img_array.reshape(1, 48, 48, -1)
    predictions = model.predict([img_array])
    score = tf.nn.softmax(predictions[0])
    print(emotion[str(np.argmax(score))])
    print(score)
    print(np.argmax(score))
    emotion_count[np.argmax(score)]+=1
            
            
    font = cv.FONT_HERSHEY_SIMPLEX
    fontScale = 2
    thickness = 4
    color = (255, 0, 0)
    pos = (50, 50)
    frame = cv.putText(frame, emotion[str(np.argmax(score))], pos, font, fontScale, color, thickness, cv.LINE_AA)
#         except:
#             pass
        #print(t)
        #t+=1
    cv.imshow("Final", frame)
cap.release()
cv.destroyAllWindows()
# return emotion[str(np.argmax(emotion_count))]

OSError: SavedModel file does not exist at: model_4.model/{saved_model.pbtxt|saved_model.pb}

In [6]:
# genre_emo = {
#     'Afraid',
#     'Angry',
#     'Disgust',
#     'Happy',
#     'Neutral',
#     'Sad',
#     'Surprise'
# }

In [7]:
directory = 'test.mp4'
emotion_out = video_feed(directory)

Sad
tf.Tensor(
[0.1625344  0.15495239 0.12709251 0.12655836 0.13287224 0.17190357
 0.12408656], shape=(7,), dtype=float32)
5
Sad
tf.Tensor(
[0.16232027 0.15487967 0.12705444 0.12661864 0.13285331 0.17224091
 0.1240327 ], shape=(7,), dtype=float32)
5
Sad
tf.Tensor(
[0.16201513 0.15479757 0.12697771 0.12665926 0.13297705 0.17256042
 0.12401283], shape=(7,), dtype=float32)
5
Sad
tf.Tensor(
[0.16294049 0.15691137 0.12738691 0.1274169  0.13242917 0.16865562
 0.12425953], shape=(7,), dtype=float32)
5
Sad
tf.Tensor(
[0.16292857 0.15679106 0.12752174 0.12736796 0.13244641 0.16865887
 0.12428548], shape=(7,), dtype=float32)
5
Sad
tf.Tensor(
[0.16247357 0.1569885  0.12749563 0.12763987 0.13240051 0.16874124
 0.12426078], shape=(7,), dtype=float32)
5
Sad
tf.Tensor(
[0.15239522 0.15981865 0.13175036 0.13724282 0.13239451 0.16119032
 0.12520814], shape=(7,), dtype=float32)
5
Sad
tf.Tensor(
[0.15236555 0.15966487 0.13166127 0.13728203 0.13237455 0.16146265
 0.12518908], shape=(7,), dtype=float32)
5


Angry
tf.Tensor(
[0.14942095 0.16539711 0.13037565 0.13852856 0.13207527 0.15938963
 0.12481286], shape=(7,), dtype=float32)
1
Angry
tf.Tensor(
[0.14929856 0.16534087 0.13027306 0.13855368 0.13211386 0.1596133
 0.12480666], shape=(7,), dtype=float32)
1
Angry
tf.Tensor(
[0.14932339 0.16525035 0.13032842 0.13848244 0.13213605 0.15965934
 0.12482005], shape=(7,), dtype=float32)
1
Sad
tf.Tensor(
[0.14868301 0.1573453  0.12946747 0.13751726 0.13336629 0.16888607
 0.12473464], shape=(7,), dtype=float32)
5
Sad
tf.Tensor(
[0.1486307  0.15746757 0.12958507 0.1376203  0.13332829 0.16862755
 0.12474056], shape=(7,), dtype=float32)
5
Sad
tf.Tensor(
[0.14858015 0.15747768 0.12954083 0.13768116 0.13334464 0.16863199
 0.12474362], shape=(7,), dtype=float32)
5
Sad
tf.Tensor(
[0.14848168 0.1575316  0.12955455 0.13778083 0.13338187 0.1685193
 0.12475012], shape=(7,), dtype=float32)
5
Sad
tf.Tensor(
[0.14787516 0.15792662 0.12920436 0.13702819 0.13399586 0.16930774
 0.12466203], shape=(7,), dtype=float32

In [8]:
len(emotion_count)

7