In [13]:
import numpy as np
import cv2
import os
import matplotlib.pyplot as plt
from tqdm import tqdm

In [14]:
DATADIR = '/home/arjun/DM/Face/train/'
CATEGORIES = ["0","1","2","3","4","5","6"]
IMG_SIZE = 48

In [15]:
training_data = []

def create_training_data():
    for category in CATEGORIES:  

        path = os.path.join(DATADIR,category)  
        class_num = CATEGORIES.index(category)  # get the classification  (0-9)

        for img in tqdm(os.listdir(path)):  # iterate over each image per dogs and cats
            try:
                img_array = cv2.imread(os.path.join(path,img) ,cv2.IMREAD_GRAYSCALE)  # convert to array
                new_array = cv2.resize(img_array, (IMG_SIZE, IMG_SIZE))  # resize to normalize data size
                training_data.append([new_array, class_num])  # add this to our training_data
            except Exception as e:  # in the interest in keeping the output clean...
                pass

In [16]:
create_training_data()

print(len(training_data))

100%|██████████| 3205/3205 [00:00<00:00, 10191.42it/s]

28821


In [17]:
import random
random.shuffle(training_data)

In [18]:
X = []
y = []

for features,label in training_data:
    X.append(features)
    y.append(label)

print(X[0].reshape(-1, IMG_SIZE, IMG_SIZE, 1))


X = np.array(X).reshape(-1, IMG_SIZE, IMG_SIZE, 1)
print(X[0].shape)

[[[[252]
   [252]
   [249]
   ...
   [241]
   [252]
   [251]]

  [[251]
   [255]
   [248]
   ...
   [227]
   [245]
   [254]]

  [[254]
   [248]
   [255]
   ...
   [246]
   [234]
   [252]]

  ...

  [[252]
   [252]
   [252]
   ...
   [252]
   [252]
   [252]]

  [[252]
   [252]
   [252]
   ...
   [252]
   [252]
   [252]]

  [[252]
   [252]
   [252]
   ...
   [252]
   [252]
   [252]]]]
(48, 48, 1)


In [19]:
import pickle

pickle_out = open("/home/arjun/DM/face_X.pickle","wb")
pickle.dump(X, pickle_out)
pickle_out.close()

pickle_out = open("/home/arjun/DM/face_Y.pickle","wb")
pickle.dump(y, pickle_out)
pickle_out.close()

In [20]:
pickle_in = open("/home/arjun/DM/face_X.pickle","rb")
X = pickle.load(pickle_in)

pickle_in = open("/home/arjun/DM/face_Y.pickle","rb")
y = pickle.load(pickle_in)

In [21]:
print(y)

[0, 3, 4, 3, 2, 4, 4, 0, 4, 5, 3, 0, 2, 0, 2, 0, 1, 3, 3, 2, 5, 2, 1, 6, 3, 0, 0, 4, 3, 5, 4, 4, 4, 3, 6, 2, 4, 4, 6, 6, 5, 0, 3, 0, 4, 3, 4, 5, 0, 2, 5, 0, 3, 2, 3, 4, 4, 2, 6, 3, 3, 3, 6, 3, 2, 5, 3, 3, 4, 0, 5, 3, 2, 0, 3, 5, 0, 0, 2, 5, 3, 3, 3, 0, 3, 5, 3, 4, 5, 6, 1, 2, 4, 2, 1, 4, 3, 1, 0, 5, 4, 3, 5, 4, 2, 5, 2, 5, 1, 3, 3, 0, 3, 3, 5, 5, 3, 4, 3, 0, 2, 3, 4, 0, 0, 2, 5, 3, 3, 2, 4, 4, 0, 3, 0, 5, 0, 6, 0, 3, 5, 4, 3, 4, 2, 3, 3, 3, 4, 4, 6, 4, 4, 6, 3, 2, 2, 5, 4, 3, 5, 3, 5, 3, 4, 2, 3, 3, 0, 5, 4, 6, 2, 0, 4, 6, 2, 2, 5, 5, 5, 6, 0, 2, 3, 2, 3, 3, 1, 0, 6, 5, 2, 4, 5, 4, 4, 0, 4, 4, 4, 4, 6, 4, 6, 3, 5, 3, 5, 3, 5, 4, 5, 5, 2, 3, 3, 1, 0, 2, 6, 4, 5, 5, 5, 3, 4, 2, 1, 3, 3, 2, 4, 3, 4, 5, 5, 3, 4, 4, 6, 3, 2, 3, 3, 3, 5, 2, 3, 3, 3, 2, 2, 4, 3, 3, 2, 2, 3, 5, 6, 4, 0, 5, 6, 3, 5, 3, 2, 4, 3, 6, 3, 5, 4, 3, 4, 3, 0, 2, 3, 4, 4, 5, 5, 3, 0, 5, 4, 6, 6, 2, 3, 0, 0, 6, 4, 3, 3, 4, 6, 3, 4, 5, 3, 4, 6, 3, 3, 2, 5, 4, 5, 3, 6, 0, 2, 2, 4, 3, 0, 3, 2, 4, 2, 4, 0, 5, 5, 4, 2, 6, 3, 

In [22]:
len(X)

28821